routes:

  login:
    pattern: '{action}/'
    controller: Index
    action: "login|logout|init|users"

  controller_action:
    pattern: '{controller}/({action}/)?'

  index:
    pattern: '/'

security:
  events:
    security.unauthenticated:
      class: Security


events:
  route.notFound:
    - '\Admin\Controllers\ApplicationController'
    - 'onRouteNotFound'
  security.unauthenticated:
    - '\Admin\Controllers\ApplicationController'
    - 'onUnauthenticated'

